esphome:
  name: bare-conductive

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "bare-conductive Fallback Hotspot"
    password: !secret wifi_fallback_hotspot_password

captive_portal:

sensor:
  - platform: uptime
    name: Uptime

text_sensor:
  - platform: template
    name: "UART Received Data"
    id: uart_received_data

uart:
    baud_rate: 115200
    tx_pin: GPIO1
    rx_pin: GPIO3
    debug:
      direction: RX
      dummy_receiver: true
      after:
        delimiter: "\r\n"
      sequence:
        - lambda: |-
            UARTDebug::log_string(direction, bytes);
            std::string str(bytes.begin(), bytes.end());
            id(uart_received_data).publish_state(str.c_str());
