substitutions:
  name: bedroom-radiator

esphome:
  name: ${name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:

sensor:
  - platform: dallas_temp
    address: 0x5d00000056c75a28
    name: 0x5d00000056c75a28
    update_interval: 10s
  - platform: dallas_temp
    address: 0x99000000371bf128
    name: 0x99000000371bf128
    update_interval: 10s


one_wire:
  - platform: gpio
    pin: D3
