esphome:
  name: ble-sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "GVCmRtvFktFbg6cwfvuOWVFyT0JD01BF+HWhRBZ/zEs="

ota:
  password: "ee95be1c8525ab5f2e5ed4501b5b558a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ble-Sensor Fallback Hotspot"
    password: "2vA41MEFIhfw"

captive_portal:

esp32_ble_tracker:

uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 9600

sensor:
  - platform: sds011
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
    update_interval: 5min
