esphome:
  name: boilersensor
  # esp-b5a228

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: !secret ota_password_old_arduinoota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Boilersensor Fallback Hotspot"
    password: "VpL0y8o1ChlT"

captive_portal:

#[03:40:06][D][dallas.sensor:084]:     0x1b000004baac9628
#[03:40:06][D][dallas.sensor:084]:     0x630121144ed00328
#[03:40:06][D][dallas.sensor:084]:     0x5a0121142bddd328
#[03:40:06][D][dallas.sensor:084]:     0x060300a27927eb28

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
  - platform: dallas_temp
    address: 0x1B000004BAAC9628
    name: "Boiler Cool Return West"
    update_interval: 10s
  - platform: dallas_temp
    address: 0x060300A27927EB28
    name: "Boiler Cool Return East"
    update_interval: 10s
  - platform: dallas_temp
    address: 0x5a0121142bddd328
    name: "Boiler Hot Supply"
    update_interval: 10s
  - platform: dallas_temp
    address: 0x630121144ed00328
    name: "Boiler Hot Exit"
    update_interval: 10s
  - platform: dallas_temp
    address: 0x7500000086bb8228
    name: "Shower Hot"
    update_interval: 10s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    mac_address:
      name: ESP Mac Wifi Address

one_wire:
  - platform: gpio
    pin: GPIO2
  
#[03:07:57][D][dallas.sensor:081]:     0x5D0301A279FB3428 # hot supply # id=\"2834fb79a201035d\
#[03:07:57][D][dallas.sensor:081]:     0x1B000004BAAC9628 # east # id=\"28eb2779a2000306\"
#[03:07:57][D][dallas.sensor:081]:     0x060300A27927EB28 # west # id=\"2896acba0400001b\"
