esphome:
  name: boiler-control

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  password: "70407aa79c7136e9237bf47533e5c363"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Boiler-Control Fallback Hotspot"
    password: "uLpewWBdQ1UQ"

captive_portal:

switch:
  - platform: gpio
    name: East
    id: boiler_control_east
    pin:
      number: D2
      mode: OUTPUT
      inverted: true
  - platform: gpio
    name: West
    id: boiler_control_west
    pin:
      number: D7
      mode: OUTPUT
      inverted: true

sensor:
  - platform: dallas
    address: 0xd90000052d382e28
    name: "West encap sensor"
    id: boiler_control_west_sensor


dallas:
  - pin: D5
