esphome:
  name: boiler-control

esp8266:
  board: d1_mini
  restore_from_flash: true

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: "70407aa79c7136e9237bf47533e5c363"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Boiler-Control Fallback Hotspot"
    password: "uLpewWBdQ1UQ"

captive_portal:

switch:
  - platform: gpio
    name: East
    id: boiler_control_east
    pin:
      number: D2
      mode: OUTPUT
      inverted: true
  - platform: gpio
    name: West
    id: boiler_control_west
    pin:
      number: D7
      mode: OUTPUT
      inverted: true

sensor:
  - platform: uptime
    name: Uptime
  - platform: dallas_temp
    address: 0xd90000052d382e28
    name: "West encap sensor"
    id: boiler_control_west_sensor
  - platform: dallas_temp
    address: 0xd20000052d567728
    name: "East encap sensor"
    id: boiler_control_east_sensor
  - platform: dallas_temp
    address: 0x4e00000084afb428
    name: "East kids BR"
    id: boiler_control_east_kids_br_sensor
  - platform: template
    name: "East virtual sensor"
    id: east_virtual_sensor
    unit_of_measurement: "°C"
    lambda: |-
      if (strcmp(id(east_selected_sensor).state.c_str(), "Dining Room Sensor") == 0) {
        return id(boiler_control_east_sensor).state;
      } else {
        return id(boiler_control_east_kids_br_sensor).state;
      }
    update_interval: 5s
    device_class: temperature
    state_class: measurement

select:
  - platform: template
    name: "East zone selected sensor"
    id: east_selected_sensor
    options:
      - "Dining Room Sensor"
      - "Kids BR Sensor"
    initial_option: "Dining Room Sensor"
    optimistic: true
    restore_value: true

one_wire:
  - platform: gpio
    pin: D5

climate:
  - platform: thermostat
    name: "East (esp)"
    sensor: east_virtual_sensor
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 68 °F
      - name: Away
        default_target_temperature_low: 60 °F
      - name: Vacation
        default_target_temperature_low: 50 °F
    min_heating_off_time: 60s
    min_heating_run_time: 60s
    min_idle_time: 30s
    heat_deadband: 0.3 °C
    heat_overrun: 0.3 °C
    heat_action:
      - switch.turn_on: boiler_control_east
    idle_action:
      - switch.turn_off: boiler_control_east
  - platform: thermostat
    name: "West (esp)"
    sensor: boiler_control_west_sensor
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 68 °F
      - name: Away
        default_target_temperature_low: 60 °F
      - name: Vacation
        default_target_temperature_low: 50 °F
    min_heating_off_time: 60s
    min_heating_run_time: 60s
    min_idle_time: 30s
    heat_deadband: 0.3 °C
    heat_overrun: 0.3 °C
    heat_action:
      - switch.turn_on: boiler_control_west
    idle_action:
      - switch.turn_off: boiler_control_west

