esphome:
  name: conductive-paint
  friendly_name: conductive-paint

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "04weXggsEF2iuApTkhEDBK5J6DLQgO010L051DWCcIs="

ota:
  - platform: esphome
    password: "1f5d4e8d726f120de7e793bf97812556"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Conductive-Paint"
    password: "RjGJLvOBSlJE"

captive_portal:
    