esphome:
  name: desk-power
  friendly_name: desk-power

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_psk

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "desk-power Fallback Hotspot"
    password: !secret wifi_fallback_hotspot_password

captive_portal:


sensor:
  - platform: uptime
    name: Uptime
  
binary_sensor:
  - platform: status
    name: Status
