esphome:
  name: eightbuttons
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:

binary_sensor:
  - platform: gpio
    pin:
      number: D1  # GPIO5
      mode: INPUT_PULLUP
      inverted: true
    name: "Button 1 green-right"

  - platform: gpio
    pin:
      number: D2  # GPIO4
      mode: INPUT_PULLUP
      inverted: true
    name: "Button 2 green-left"

  - platform: gpio
    pin:
      number: D3  # GPIO0 (boot-sensitive, needs care)
      mode: INPUT_PULLUP
      inverted: true
    name: "Button 3 blue-right"

  - platform: gpio
    pin:
      number: D4  # GPIO2 (boot-sensitive)
      mode: INPUT_PULLUP
      inverted: true
    name: "Button 4 blue-left"

  - platform: gpio
    pin:
      number: D5  # GPIO14
      mode: INPUT_PULLUP
      inverted: true
    name: "Button 5 yellow-right"

  - platform: gpio
    pin:
      number: D6  # GPIO12
      mode: INPUT_PULLUP
      inverted: true
    name: "Button 6 yellow-left"

  - platform: gpio
    pin:
      number: D7  # GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "Button 7 red-right"

  - platform: gpio
    pin:
      number: D8  # GPIO15 (must be LOW at boot)
      mode: INPUT
      inverted: false  # Button pulls HIGH when pressed
    name: "Button 8 red-left"

