substitutions:
  name: esp746cdb

esphome:
  name: $name
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password_old_arduinoota

sensor:
  - platform: dht
    pin: D3
    temperature:
      name: "$name Temperature"
    humidity:
      name: "$name Humidity"
    model: AM2302
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: ultrasonic
    id: esp746cdb_ultrasonic
    trigger_pin: D8
    echo_pin: D7
    name: "Ultrasonic Sensor"
    timeout: 3.0m

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    mac_address:
      name: ESP MAC Address
  - platform: template
    name: "$name Garage Status"
    lambda: |-
      float val;
      val = id(esp746cdb_ultrasonic).state;
      if (val > 2)
          return std::string("Door closed, Empty");
      if (val < 0.2)
          return std::string("Door open");
      if (val > 0.5 && val < 1.0)
          return std::string("Door closed, Car In");
      return std::string("Unknown status");

switch:
 - platform: gpio
   pin:
     number: GPIO2
     inverted: true
   name: "LED"
 - platform: gpio
   pin:
     number: D5
   name: "Garage Door"
   id: garage_door_opener_relay
   on_turn_on:
     - delay: 500ms
     - switch.turn_off: garage_door_opener_relay
