esphome:
  name: esp746cdb
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: 'rumbledethumps'
  password: 'youneedatray'

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "iaY3TO4hYeyMvp1jLpZYXfAjC003kxReGma8NH2DO0gCzZoGP1"

sensor:
  - platform: dht
    pin: D3
    temperature:
      name: "esp746cdb Temperature"
    humidity:
      name: "esp746cdb Humidity"
    model: AM2302
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    mac_address:
      name: ESP Mac Wifi Address

switch:
 - platform: gpio
   pin:
     number: GPIO2
     inverted: true
   name: "LED"
 - platform: gpio
   pin:
     number: D5
     #inverted: true
   name: "Relay"