esphome:
  name: esp746cdb
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password_old_arduinoota

sensor:
  - platform: dht
    pin: D3
    temperature:
      name: "esp746cdb Temperature"
    humidity:
      name: "esp746cdb Humidity"
    model: AM2302
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    mac_address:
      name: ESP MAC Address

switch:
 - platform: gpio
   pin:
     number: GPIO2
     inverted: true
   name: "LED"
 - platform: gpio
   pin:
     number: D5
   name: "Garage Door"
   id: garage_door_opener_relay
   on_turn_on:
     - delay: 500ms
     - switch.turn_off: garage_door_opener_relay
