substitutions:
  name: esphome-web-005a15
  friendly_name: radiator-control-1

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:

stepper:
  - platform: a4988
    id: my_stepper_1
    step_pin: D5
    dir_pin: D6
    max_speed: 250 steps/s

    # Optional:
    sleep_pin: D2
    #acceleration: inf
    #deceleration: inf

button:
  - platform: template
    name: "Decrement Stepper by 1"
    id: decrement_button
    on_press:
      - stepper.set_target:
          id: my_stepper_1
          target: !lambda |-
            return id(my_stepper_1).target_position - 1;

  - platform: template
    name: "Increment Stepper by 1"
    id: increment_button
    on_press:
      - stepper.set_target:
          id: my_stepper_1
          target: !lambda |-
            return id(my_stepper_1).target_position + 1;

sensor:
  - platform: template
    name: "Stepper: current_position"
    lambda: |-
        return id(my_stepper_1).current_position;
    update_interval: 1s
  - platform: template
    name: "Stepper: target_position"
    lambda: |-
        return id(my_stepper_1).target_position;
    update_interval: 1s