substitutions:
  name: gardener

esphome:
  name: $name

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_psk

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gardener Fallback Hotspot"
    password: !secret wifi_fallback_hotspot_password

captive_portal:


sensor:
  - platform: adc
    pin: A0
    name: "Capacitive Soil Moisture Sensor"
    update_interval: 60s
    id: capacitive_soil_moisture_sensor
  - platform: template
    lambda: |-
      return id(capacitive_soil_moisture_sensor).state;
    filters:
      calibrate_linear:
        - 0.65 -> 0
        - 0.25 -> 100
    unit_of_measurement: "%"
    name: "% Wet"
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: Uptime Sensor
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    mac_address:
      name: ESP MAC Address

switch:
  - platform: gpio
    pin:
      number: GPIO2
      inverted: true
    name: "LED"
    entity_category: "diagnostic"
  - platform: gpio
    pin:
      number: D5
    name: "Valve"

button:
  - platform: restart
    name: "$name restart"
