esphome:
  name: humidifier
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  platform: esphome
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test3 Fallback Hotspot"
    password: "ytGbajMuzifO"

captive_portal:

switch:
  - platform: gpio
    pin:
      number: D4
      inverted: true
    name: "test3 esp8266 LED"

sensor:
  - platform: ultrasonic
    trigger_pin: D5
    echo_pin: D1
    update_interval: 10s
    name: "test3 esp8266 ultrasonic sensor"
    accuracy_decimals: 5
    id: ultrasonic_sensor
  - platform: template
    lambda: |-
      return id(ultrasonic_sensor).state;
    filters:
      calibrate_linear:
        - 0.23 -> 0
        - 0.185 -> 100
    unit_of_measurement: "%"
    name: "% Full"
