esphome:
  name: hvac-sensor

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "983939258e8f6912a6e3bae1a5d66fcb"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hvac-Sensor Fallback Hotspot"
    password: "KhD0LTjOCYAn"

captive_portal:

sensor:
  - platform: dallas
    address: 0xe4000004bbd15428
    name: "supply"
    id: hvac_sensor_supply
  - platform: dallas
    address: 0x5d0301a279fb3428
    name: "return"
    id: hvac_sensor_return
  - platform: template
    name: delta_t
    lambda: |-
      return (id(hvac_sensor_supply).state - id(hvac_sensor_return).state);
    id: hvac_sensor_delta_t
    unit_of_measurement: "°C"
  - platform: template
    name: delta_t_f
    lambda: |-
      return ((id(hvac_sensor_supply).state*9/5+32) - (id(hvac_sensor_return).state*9/5+32));
    id: hvac_sensor_delta_t_f
    unit_of_measurement: "°F"

dallas:
  - pin: D5
