esphome:
  name: jeeoa
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "48e320bcabc00458f7a26e8724a49b48"

wifi:
  ssid: "rumbledethumps"
  password: !secret rumbledethumps_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jeeoa Fallback Hotspot"
    password: "Inwdnb5Pgwat"

captive_portal:

binary_sensor:
  - platform: status
    name: Socket Status
    device_class: connectivity
  - platform: gpio
    id: button
    internal: true
    pin:
      number: 13
      mode: INPUT
      inverted: true
    on_press:
      - then:
          - switch.toggle:
              id: socket_relay
    name: button

switch:
  - platform: gpio
    name: Socket
    id: socket_relay
    pin:
      number: 15
      mode: OUTPUT
      inverted: false
    on_turn_on:
      - then:
          - light.turn_on:
              id: status_led
              state: true
    on_turn_off:
      - then:
          - light.turn_off:
              id: status_led
              state: false
    restore_mode: RESTORE_DEFAULT_OFF
    interlock_wait_time: 0ms

  - platform: restart
    name: Socket Restart

output:
  - platform: gpio
    id: led
    pin:
      number: 0
      inverted: true
      mode: OUTPUT

light:
  - platform: binary
    name: Status LED
    id: status_led
    internal: true
    output: led
    restore_mode: RESTORE_DEFAULT_OFF

sensor:
  - platform: wifi_signal
    name: Socket Wifi Signal
    id: socket_wifi_signal
    update_interval: 15s
    force_update: false
    unit_of_measurement: dB
    icon: mdi:wifi
    accuracy_decimals: 0

text_sensor:
  - platform: wifi_info
    mac_address:
      name: Socket MAC Address
      icon: mdi:network