esphome:
  name: orbit-control

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "orbit-control Fallback Hotspot"
    password: !secret wifi_fallback_hotspot_password

captive_portal:

switch:
  - platform: gpio
    name: D1
    pin:
      number: D1
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: D2
    pin:
      number: D2
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: D3
    pin:
      number: D3
      mode: OUTPUT
      inverted: false
