esphome:
  name: power-monitor
  platform: ESP32
  # Board is an ESP32 DevKit v1 looks identical to the 36-pin version of this:
  # https://randomnerdtutorials.com/getting-started-with-esp32/
  board: esp32doit-devkit-v1

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "e35b0759bff15ebfe44cc60dc556c8b8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Power-Monitor Fallback Hotspot"
    password: "lCC48LehktSA"

captive_portal:

switch:
  - platform: gpio
    pin:
      number: GPIO2
    name: "powermon LED"

sensor:
    # one sensor
  - platform: ct_clamp
    sensor: adc_sensor_gpio34
    name: "D34 Measured Current"
    update_interval: 10s
    sample_duration: 500ms
    id: ct_clamp_gpio34
    accuracy_decimals: 5
    filters:
      - calibrate_linear:
          - 0.00291 -> 0
          - 0.00715 -> 0.71161
#          - 0.007 -> 0.692

  - platform: adc
    pin: GPIO34
    id: adc_sensor_gpio34
    name: "GPIO34 voltage"
    update_interval: 10s
    attenuation: auto
    
    # and another
  - platform: ct_clamp
    sensor: adc_sensor_gpio35
    name: "D35 Measured Current"
    update_interval: 10s
    sample_duration: 500ms
    id: ct_clamp_gpio35
    accuracy_decimals: 5
    filters:
      - calibrate_linear:
          - 0.002928 -> 0
          - 0.008817 -> 0.689101
    
  - platform: adc
    pin: GPIO35
    id: adc_sensor_gpio35
    name: "GPIO35 voltage"
    update_interval: 10s
    attenuation: auto

  - platform: template
    name: "Template Voltage"
    lambda: |-
      return 120.0;
    update_interval: 10s
    id: template_voltage
    unit_of_measurement: "V"
    icon: mdi:sine-wave

  - platform: template
    name: "Template Power D34"
    lambda: |-
      return (id(template_voltage).state * id(ct_clamp_gpio34).state);
    update_interval: 10s
    id: power_d34
    unit_of_measurement: "W"
    icon: mdi:lightning-bolt-outline

  - platform: template
    name: "Template Power D35"
    lambda: |-
      return (id(template_voltage).state * id(ct_clamp_gpio35).state);
    update_interval: 10s
    id: power_d35
    unit_of_measurement: "W"
    icon: mdi:lightning-bolt-outline

  - platform: template
    name: "Template Power SUM"
    lambda: |-
      return (id(power_d34).state + id(power_d35).state);
    update_interval: 10s
    id: template_power_sum
    unit_of_measurement: "W"
    icon: mdi:lightning-bolt-outline
    
    #power:
    #  id: my_power
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: template_power_sum
    icon: mdi:lightning-bolt

#text_sensor:
#  - platform: template
#    name: "Time"
#    lambda: |-
#      return id(homeassistant_time).now().strftime("%c");

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "America/Chicago"
