esphome:
  name: power-monitor
  platform: ESP32
  # Board is an ESP32 DevKit v1 looks identical to the 36-pin version of this:
  # https://randomnerdtutorials.com/getting-started-with-esp32/
  board: esp32doit-devkit-v1

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "e35b0759bff15ebfe44cc60dc556c8b8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Power-Monitor Fallback Hotspot"
    password: "lCC48LehktSA"

captive_portal:

switch:
  - platform: gpio
    pin:
      number: GPIO2
    name: "powermon LED"

sensor:
  - platform: wifi_signal
    name: "powermon WiFi Signal Sensor"
    update_interval: 60s
    
    # one sensor
  - platform: ct_clamp
    sensor: adc_sensor_gpio34
    name: "D34 Measured Current"
    update_interval: 60s

  - platform: adc
    pin: GPIO34
    id: adc_sensor_gpio34
    
    # and another
  - platform: ct_clamp
    sensor: adc_sensor_gpio35
    name: "D35 Measured Current"
    update_interval: 60s

  # Example source sensor
  - platform: adc
    pin: GPIO35
    id: adc_sensor_gpio35
