esphome:
  name: power-monitor
  platform: ESP32
  # Board is an ESP32 DevKit v1 looks identical to the 36-pin version of this:
  # https://randomnerdtutorials.com/getting-started-with-esp32/
  board: esp32doit-devkit-v1

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "e35b0759bff15ebfe44cc60dc556c8b8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Power-Monitor Fallback Hotspot"
    password: "lCC48LehktSA"

captive_portal:

switch:
  - platform: gpio
    pin:
      number: GPIO2
    name: "powermon LED"

sensor:
    # one sensor
  - platform: ct_clamp
    sensor: adc_sensor_gpio34
    name: "D34 Measured Current"
    update_interval: 10s
    sample_duration: 500ms
    id: ct_clamp_gpio34
    accuracy_decimals: 5
    filters:
      - calibrate_linear:
# These calibration readings are based on the basement chest freezer. Not terribly accurate when scaled up. Done 17th-18th of Jan 2022.
           - 0.00612 -> 0 # the zero point
#          - 0.00715 -> 0.71161 # chest freezer on for ~15 mins
# calibration on microwave with ~4 cups of water. about 14.8A on the genie meter but a bit more on the S31. Trusting the S31.
           - 0.16222 -> 15.13783
# calibration on kettle, ~12A
           - 0.12957 -> 12.08479
  - platform: adc
    pin: GPIO34
    id: adc_sensor_gpio34
    name: "GPIO34 voltage"
    update_interval: 10s
    attenuation: auto
    entity_category: "diagnostic"
    
    # and another
  - platform: ct_clamp
    sensor: adc_sensor_gpio35
    name: "D35 Measured Current"
    update_interval: 10s
    sample_duration: 500ms
    id: ct_clamp_gpio35
    accuracy_decimals: 5
    filters:
      - calibrate_linear:
# These calibration readings are based on the basement chest freezer. Not terribly accurate when scaled up. Done 17th-18th of Jan 2022.
           - 0.00540 -> 0 # zero point
#          - 0.008817 -> 0.689101 # chest freezer on for ~15 minutes
# calibration on microwave with ~4 cups of water vs the S31-A.
#           - 0.18208 -> 14.89117
# calibration using kettle, ~12A
#          - 0.18260 -> 12.11394
# now that i fixed polarity problem on D34 which seemed to cause D35 to be wonky:
# calibration of kettle 12A
           - 0.13035 -> 11.93600
# toaster 12A
           - 0.13467 -> 12.24786
# microwave 15A
           - 0.16145 -> 14.70408
    
  - platform: adc
    pin: GPIO35
    id: adc_sensor_gpio35
    name: "GPIO35 voltage"
    update_interval: 10s
    attenuation: auto
    entity_category: "diagnostic"

  - platform: template
    name: "Template Voltage"
    lambda: |-
      return 120.0;
    update_interval: 10s
    id: template_voltage
    unit_of_measurement: "V"
    icon: mdi:sine-wave

  - platform: homeassistant
    name: "S31-A Voltage L1 Yellow (from HA)"
    entity_id: sensor.sonoff_s31_a_voltage

  - platform: homeassistant
    name: "S31-B Voltage L2 Red (from HA)"
    entity_id: sensor.sonoff_s31_b_voltage

  - platform: template
    name: "Template Power D34"
    lambda: |-
      return (id(template_voltage).state * id(ct_clamp_gpio34).state);
    update_interval: 10s
    id: power_d34
    unit_of_measurement: "W"
    icon: mdi:lightning-bolt-outline

  - platform: template
    name: "Template Power D35"
    lambda: |-
      return (id(template_voltage).state * id(ct_clamp_gpio35).state);
    update_interval: 10s
    id: power_d35
    unit_of_measurement: "W"
    icon: mdi:lightning-bolt-outline

  - platform: template
    name: "Template Power SUM"
    lambda: |-
      return (id(power_d34).state + id(power_d35).state);
    update_interval: 10s
    id: template_power_sum
    unit_of_measurement: "W"
    icon: mdi:lightning-bolt-outline
    
    #power:
    #  id: my_power
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: template_power_sum
    icon: mdi:lightning-bolt

#text_sensor:
#  - platform: template
#    name: "Time"
#    lambda: |-
#      return id(homeassistant_time).now().strftime("%c");

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "America/Chicago"
