esphome:
  name: rainbarrel

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "82fa3ad393f40f23acb3ec0eb86b3cd2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rainbarrel Fallback Hotspot"
    password: "eAaZOCDhYzhF"

captive_portal:

sensor:
  - platform: ultrasonic
    trigger_pin: D3
    echo_pin: D4
    name: "Rain Barrel Level"
    accuracy_decimals: 5
  - platform: adc
    pin: A0
    name: "Capacitive Soil Moisture Sensor"
    update_interval: 60s
    id: capacitive_soil_moisture_sensor
  - platform: template
    lambda: |-
      return id(capacitive_soil_moisture_sensor).state;
    filters:
      calibrate_linear:
        - 0.65 -> 0
        - 0.25 -> 100
    unit_of_measurement: "%"
    name: "% Wet"
