esphome:
  name: s31-b

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

# Enable Home Assistant API
api:

ota:
  password: "1832cc362bee72fa1aa3a217b96b6ce0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "S31-B Fallback Hotspot"
    password: "9cRLcjwQDm9D"

captive_portal:

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "S31-B Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "S31-B Status"

sensor:
  - platform: wifi_signal
    name: "S31-B WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    update_interval: 10s
    current:
      name: "S31-B Current"
      accuracy_decimals: 3
    voltage:
      name: "S31-B Voltage"
      accuracy_decimals: 1
    power:
      name: "S31-B Power"
      accuracy_decimals: 1
      id: power
  - platform: total_daily_energy
    name: "S31-B Total Daily Energy"
    power_id: power
    icon: mdi:lightning-bolt
    
switch:
  - platform: gpio
    name: "S31-B Relay"
    pin: GPIO12
    id: relay

status_led:
  pin: GPIO13
  





time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "America/Chicago"
