substitutions:
  ui_name: S31-M
  update_interval: 10s

esphome:
  name: s31-m

esp8266:
  board: esp01_1m
  restore_from_flash: true

# Enable logging
logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${ui_name} Fallback Hotspot"
    password: !secret wifi_fallback_hotspot_password

captive_portal:

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${ui_name} Status"

sensor:
  - platform: wifi_signal
    name: "${ui_name} WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "${ui_name} Current"
      accuracy_decimals: 3
      filters:
        - throttle_average: ${update_interval}
    voltage:
      name: "${ui_name} Voltage"
      accuracy_decimals: 1
      filters:
        - throttle_average: ${update_interval}
    power:
      name: "${ui_name} Power"
      accuracy_decimals: 1
      id: power
      state_class: "measurement"
      filters:
        - throttle_average: ${update_interval}
    energy:
      name: "${ui_name} Energy"
      filters:
        - throttle: ${update_interval}
  - platform: total_daily_energy
    name: "${ui_name} Total Daily Energy"
    power_id: power
    icon: mdi:lightning-bolt
    
switch:
  - platform: gpio
    name: "${ui_name} Relay"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_ON

status_led:
  pin: GPIO13
  





time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "America/Chicago"
