esphome:
  name: s31

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

# Enable Home Assistant API
api:

ota:
  password: "e293995bb5a0ef2b16b926c88671cebc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "S31 Fallback Hotspot"
    password: "9cRLcjwQDm9D"

captive_portal:

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Sonoff S31 Status"

sensor:
  - platform: wifi_signal
    name: "Sonoff S31 WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    update_interval: 10s
    current:
      name: "Sonoff S31 Current"
      accuracy_decimals: 3
    voltage:
      name: "Sonoff S31 Voltage"
      accuracy_decimals: 1
    power:
      name: "Sonoff S31 Power"
      accuracy_decimals: 1
      id: power
    energy:
      name: "S31-A Energy"
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: power
    icon: mdi:lightning-bolt
    
switch:
  - platform: gpio
    name: "Sonoff S31 Relay"
    pin: GPIO12
    id: relay

status_led:
  pin: GPIO13
  





time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "America/Chicago"
